# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Alpha"
license = "Apache 2.0"
licenselink = "http://www.apache.org/licenses/LICENSE-2.0"
description = "Example for the Hugo-Brunch-Bootstrap-Boilerplate"
homepage = "https://github.com/jkuetemeier/hugo-brunch-bootstrap-boilerplate"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Jörg Kütemeier"
  homepage = "https://kuetemeier.de/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
